services:
  - type: web
    name: liquiditycon-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: liquiditycon-db
          property: connectionString
      - key: SECRET_KEY
        value: your_jwt_secret
      - key: ALGORITHM
        value: HS256
      - key: MYFXBOOK_EMAIL
        value: your_email
      - key: MYFXBOOK_PASSWORD
        value: your_password